apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scrutiny.fullname" . }}
  labels:
    {{- include "scrutiny.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "scrutiny.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "scrutiny.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "scrutiny.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
        {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.command.enabled }}
          command: [{{ .Values.command.value }}]
        {{- end }}
          args:
        {{- range $value := .Values.args }}
            - {{ $value }}
        {{- end}}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Values.Varnish.name }}
          env:
        {{- range $key, $value := .Values.Varnish.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
          securityContext:
            {{- toYaml .Values.Varnish.securityContext | nindent 12 }}
          image: "{{ .Values.Varnish.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.Varnish.image.pullPolicy }}
        {{- if .Values.Varnish.command.enabled }}
          command: [{{ .Values.Varnish.command.value }}]
        {{- end }}
          args:
        {{- range $value := .Values.Varnish.args }}
            - {{ $value }}
        {{- end}}
          ports:
            - name: {{ .Values.Varnish.service.name }}
              containerPort: {{ .Values.Varnish.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.Varnish.service.name }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.Varnish.service.name }}
          resources:
            {{- toYaml .Values.Varnish.resources | nindent 12 }}
        - name: {{ .Values.Nginx.name }}
          env:
        {{- range $key, $value := .Values.Nginx.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
          securityContext:
            {{- toYaml .Values.Nginx.securityContext | nindent 12 }}
          image: "{{ .Values.Nginx.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.Nginx.image.pullPolicy }}
        {{- if .Values.Nginx.command.enabled }}
          command: [{{ .Values.Nginx.command.value }}]
        {{- end }}
          args:
        {{- range $value := .Values.Nginx.args }}
            - {{ $value }}
        {{- end}}
          ports:
            - name: {{ .Values.Nginx.service.name }}
              containerPort: {{ .Values.Nginx.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.Nginx.resources | nindent 12 }}
        - name: {{ .Values.News.name }}
          env:
        {{- range $key, $value := .Values.News.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}
          securityContext:
            {{- toYaml .Values.News.securityContext | nindent 12 }}
          image: "{{ .Values.News.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.News.image.pullPolicy }}
        {{- if .Values.News.command.enabled }}
          command: [{{ .Values.News.command.value }}]
        {{- end }}
          args:
        {{- range $value := .Values.News.command.args }}
            - {{ $value }}
        {{- end }}
          resources:
            {{- toYaml .Values.News.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
