# Generated by Django 3.2.9 on 2021-12-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("Healthy", "Healthy"), ("Degraded", "Degraded")],
                        default="Healthy",
                        max_length=32,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
