# Generated by Django 3.2.9 on 2022-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "name",
                    models.SlugField(max_length=36, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Healthy", "Healthy"), ("Degraded", "Degraded")],
                        default="Healthy",
                        max_length=32,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
