# Generated by Django 5.0 on 2024-01-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_job_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.SlugField(max_length=255),
        ),
    ]
