version: "3"

services:
    scrutiny.local:
        image: dunglas/mercure
        restart: unless-stopped
        ports:
            - "8081:8081"
            - "8082:8082"
            - "5099:5099"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        depends_on:
            - varnish
    varnish:
        image: varnish:latest
        volumes:
            - ./default.vcl:/etc/varnish/default.vcl:ro
        depends_on:
            - web
            - static
    static:
        image: nginx:latest
        volumes:
            - ./scrutiny/static:/usr/share/nginx/html
    web:
        image: blong14/scrutiny-python
        #        image: blong14/scrutiny-pypy
        restart: unless-stopped
        environment:
            - DJANGO_SETTINGS_MODULE=scrutiny.settings.prod
            - OTEL_PYTHON_DJANGO_INSTRUMENT="True"
            - OTEL_TRACES_SAMPLER=parentbased_traceidratio
            - OTEL_TRACES_SAMPLER_ARG=0.1
            - PG_PASSWORD=!Changeme!
            - PG_USER=admin
            - PG_HOST=db
            - PG_PORT=5432
            - PG_DATABASE=scrutiny
        volumes:
            - ./scrutiny/settings:/app/scrutiny/settings
        depends_on:
            - db
            - scrape
    db:
        image: postgres:14-bullseye
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=!Changeme!
            - POSTGRES_USER=admin
            - POSTGRES_DATABASE=scrutiny
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "54321:5432"
        volumes:
            - ./pg_entrypoint.sh:/docker-entrypoint-initdb.d/initdb.sh
    scrape:
        image: blong14/scrutiny-go
        restart: unless-stopped
        command:
            - /go/bin/scrutiny
            - news
    jaeger:
        image: jaegertracing/all-in-one
        ports:
            - "6831:6831/udp"