version: "3"

services:
    scrutiny.local:
        image: dunglas/mercure
        restart: unless-stopped
        ports:
            - "8081:8081"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
    web:
        image: blong14/scrutiny
        restart: unless-stopped
        environment:
            - DJANGO_SETTINGS_MODULE=scrutiny.settings.prod
        ports:
            - "8080:8080"
        volumes:
            - ./scrutiny/settings:/app/scrutiny/settings
        depends_on:
            - scrutiny.local
    scrape:
        image: blong14/scrutiny
        restart: unless-stopped
        ports:
            - "9000:9000"
        command:
            - ./bin/scrutiny
            - news
        depends_on:
            - web