version: "3"

services:
    scrutiny.local:
        image: dunglas/mercure
        restart: unless-stopped
        ports:
            - "8089:8089"
            - "5099:5099"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
    static:
        image: nginx:latest
        ports:
            - "8090:80"
        volumes:
            - ./scrutiny/static:/usr/share/nginx/html
    web:
        image: blong14/scrutiny
        restart: unless-stopped
        environment:
            - CR_HOST=cockroach-0
            - DJANGO_SETTINGS_MODULE=scrutiny.settings.dev
            - OTEL_PYTHON_DJANGO_INSTRUMENT="True"
            - OTEL_TRACES_SAMPLER=parentbased_traceidratio
            - OTEL_TRACES_SAMPLER_ARG=0.1
        ports:
            - "8082:8080"
        volumes:
            - .:/app
        depends_on:
            - cockroach-0
    cockroach-0:
        image: cockroachdb/cockroach:latest
        command: start --insecure --join=cockroach-0
        ports:
            - "26257:26257"
            - "8080:8080"
    postgres:
        image: postgres:15
        ports:
            - "54321:5432"
        environment:
            POSTGRES_USER: pi
            POSTGRES_PASSWORD: test
            POSTGRES_DB: scrutiny
    jaeger:
        image: jaegertracing/all-in-one
        ports:
            - "6831:6831/udp"