version: "3"

services:
    scrutiny.local:
        image: dunglas/mercure
        restart: unless-stopped
        ports:
            - "8081:8081"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./scrutiny/assets/images:/images
            - ./scrutiny/static:/static
    web:
        image: blong14/scrutiny-python
#        image: blong14/scrutiny-pypy
        restart: unless-stopped
        environment:
            - DJANGO_SETTINGS_MODULE=scrutiny.settings.prod
            - OTEL_PYTHON_DJANGO_INSTRUMENT="True"
            - OTEL_TRACES_SAMPLER=parentbased_traceidratio
            - OTEL_TRACES_SAMPLER_ARG=0.1
        volumes:
            - ./scrutiny/settings:/app/scrutiny/settings
        depends_on:
            - scrutiny.local
    scrape:
        image: blong14/scrutiny-go
        restart: unless-stopped
        command:
            - /go/bin/scrutiny
            - news
        depends_on:
            - web
    jaeger:
        image: jaegertracing/all-in-one
        ports:
            - "16686:16686"
            - "6831:6831/udp"