# Generated by Django 3.2.9 on 2021-12-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(max_length=256)),
                ("points", models.IntegerField()),
                ("slug", models.CharField(max_length=36)),
                ("text", models.TextField(default="", null=True)),
                ("title", models.CharField(max_length=256)),
                (
                    "type",
                    models.CharField(
                        choices=[("STORY", "story"), ("COMMENT", "comment")],
                        default="STORY",
                        max_length=32,
                    ),
                ),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="news.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "get_latest_by": "points",
            },
        ),
    ]
