# Generated by Django 3.2.9 on 2021-12-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("story_id", models.BigIntegerField()),
                ("posted_by", models.CharField(max_length=256)),
                ("score", models.IntegerField()),
                (
                    "slug",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("story_url", models.URLField()),
                ("time", models.DateTimeField()),
                ("title", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-time"],
            },
        ),
    ]
