# Generated by Django 3.2.2 on 2022-01-26 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("STORY_ADDED", "story_added")],
                        default="STORY_ADDED",
                        max_length=32,
                    ),
                ),
                ("event_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
