# Generated by Django 4.0.2 on 2022-02-25 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
