# Generated by Django 4.2.7 on 2023-11-11 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0003_delete_event_delete_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("feed_id", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256)),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
