# Generated by Django 4.2.7 on 2023-11-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
