# Generated by Django 4.0.2 on 2022-02-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
