# Generated by Django 4.0.3 on 2022-03-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_alter_note_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="neighbors",
            field=models.JSONField(null=True),
        ),
    ]
